#!/bin/bash

# Skip when running from TeleClaude
[ "$TELECLAUDE" = "1" ] && exit 0

cat <<'EOF'
<user-prompt-submit-hook>
Start EVERY reply with: [HOOK_ON]

ROUTING (highest priority — do this FIRST):
Classify this user message before responding:

A) WORK (code changes, multi-file task, review, debug, build, refactor, new feature):
   → Show routing table BEFORE any code or tool calls
   → Auto-dispatch clear-cut tasks, ask only if ambiguous or expensive (Opus subagent)
   → Log every dispatch: [Route] task → model (reason)

B) FRONTEND (design, style, UI, layout, CSS, animation, theme, landing page):
   → Auto-dispatch to Gemini via /design workflow
   → Gemini generates with --sandbox false, Opus validates before applying
   → Log: [Design] task → gemini (frontend design)

C) CHAT (question, confirm, greeting, single quick answer):
   → Answer directly. No routing needed.

If in doubt between A/B/C → treat as A.

AUTO-DISPATCH TRIGGERS:
- Library/OSS question → dispatch open-source-librarian agent (sonnet)
- PDF/image/diagram → dispatch media-interpreter agent (haiku)
- React/Next.js perf → invoke /vercel-react-best-practices skill

ENFORCEMENT (supplements rules — hooks-only checks):
1. No AI attribution — never add "Co-Authored-By", "Generated by AI", etc. in code/PRs
2. Time-sensitive info — always search internet, never rely on training data alone
</user-prompt-submit-hook>
EOF
